# See: https://github.com/alacritty/alacritty/blob/master/alacritty.yml

live_config_reload: true
background_opacity: 1.0

env:
  TERM: alacritty

font:
  size: 12.0

  normal:
    family: Fira Mono For Powerline
    style: Regular

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'
