# See: https://github.com/alacritty/alacritty/blob/master/alacritty.yml

live_config_reload: true
background_opacity: 0.8

env:
  TERM: alacritty

font:
  size: 12.0

  normal:
    family: Fira Mono For Powerline
    style: Regular

colors:
  primary:
    background: '#282828'
    foreground: '#ebdbb2'

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

window:
  dynamic_padding: false
  decorations: none
  
  padding:
    x: 0
    y: 0

key_bindings:
  - { key: Escape,  mode: Vi, action: ToggleViMode }
